<?php

add_action('acf/include_fields', function () {
	if (!function_exists('acf_add_local_field_group')) {
		return;
	}

	acf_add_local_field_group(array(
		'key' => 'group_55c35b2622bf5',
		'title' => 'Principio activo',
		'fields' => array(
			array(
				'key' => 'field_55c35b2e5e06b',
				'label' => 'Principio activo',
				'name' => 'principio_activo',
				'aria-label' => '',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'Aceite de Eucalipto' => 'Aceite de Eucalipto',
					'Acetato de Glatiramer' => 'Acetato de Glatiramer',
					'Acetato de ciproterona' => 'Acetato de ciproterona',
					'Acetazolamida' => 'Acetazolamida',
					'Aciclovir' => 'Aciclovir',
					'Alcanfor' => 'Alcanfor',
					'Alcohol polivinílico' => 'Alcohol polivinílico',
					'Almidón de Maíz' => 'Almidón de Maíz',
					'Alprazolam' => 'Alprazolam',
					'Amikacina (como sulfato)' => 'Amikacina (como sulfato)',
					'Amitriptilina clorhidrato' => 'Amitriptilina clorhidrato',
					'Amlodipino (como besilato)' => 'Amlodipino (como besilato)',
					'Amoxicilina' => 'Amoxicilina',
					'Amoxicilina (como trihidrato)' => 'Amoxicilina (como trihidrato)',
					'Anfebutamona Clorhidrato (Bupropión)' => 'Anfebutamona Clorhidrato (Bupropión)',
					'Anfepramona clorhidrato' => 'Anfepramona clorhidrato',
					'Armodafinilo' => 'Armodafinilo',
					'Atazanavir' => 'Atazanavir',
					'Atenolol' => 'Atenolol',
					'Atorvastatina (como Atorvastatina Cálcica forma I Trihidrato)' => 'Atorvastatina (como Atorvastatina Cálcica forma I Trihidrato)',
					'Atorvastatina (como Atorvastatina cálcica cristalina forma VIII)' => 'Atorvastatina (como Atorvastatina cálcica cristalina forma VIII)',
					'Atropina sulfato' => 'Atropina sulfato',
					'Azitromicina' => 'Azitromicina',
					'Azitromicina (como dihidrato)' => 'Azitromicina (como dihidrato)',
					'Bacitracina' => 'Bacitracina',
					'Balitarían' => 'Balitarían',
					'Beclometasona dipropionato' => 'Beclometasona dipropionato',
					'Bendamustina Clorhidrato' => 'Bendamustina Clorhidrato',
					'Benserazida clorhidrato' => 'Benserazida clorhidrato',
					'Betametasona' => 'Betametasona',
					'Betametasona (como Dipropionato)' => 'Betametasona (como Dipropionato)',
					'Betametasona Acetato Micronizada' => 'Betametasona Acetato Micronizada',
					'Betametasona Sodio Fosfato' => 'Betametasona Sodio Fosfato',
					'Betametosona Acetato Micronizada' => 'Betametosona Acetato Micronizada',
					'Betaxolol (como clorhidrato)' => 'Betaxolol (como clorhidrato)',
					'Bisoprolol Fumarato' => 'Bisoprolol Fumarato',
					'Bortezomib' => 'Bortezomib',
					'Bromazepam' => 'Bromazepam',
					'Budesonida' => 'Budesonida',
					'Cafeína' => 'Cafeína',
					'Calcio (como carbonato)' => 'Calcio (como carbonato)',
					'Calcio carbonato' => 'Calcio carbonato',
					'Capecitabina' => 'Capecitabina',
					'Carbamazepina' => 'Carbamazepina',
					'Carbidopa (como monohidrato)' => 'Carbidopa (como monohidrato)',
					'Carbonato de calcio' => 'Carbonato de calcio',
					'Carvedilol' => 'Carvedilol',
					'Cefadroxilo (como monohidrato)' => 'Cefadroxilo (como monohidrato)',
					'Cefazolina' => 'Cefazolina',
					'Ceftriaxona' => 'Ceftriaxona',
					'Celecoxib' => 'Celecoxib',
					'Cetirizina diclorhidrato' => 'Cetirizina diclorhidrato',
					'Ciclobenzaprina' => 'Ciclobenzaprina',
					'Ciclobenzaprina clorhidrato' => 'Ciclobenzaprina clorhidrato',
					'Ciclosporina' => 'Ciclosporina',
					'Cilastatina Sódica' => 'Cilastatina Sódica',
					'Cinarizina' => 'Cinarizina',
					'Ciprofloxacino (como clorhidrato monohidrato)' => 'Ciprofloxacino (como clorhidrato monohidrato)',
					'Citalaprom (como bromhidrato)' => 'Citalaprom (como bromhidrato)',
					'Citalopram' => 'Citalopram',
					'Citalopram (como bromhidrato)' => 'Citalopram (como bromhidrato)',
					'Citrato de Sodio' => 'Citrato de Sodio',
					'Claritromicina' => 'Claritromicina',
					'Clidinio bromuro' => 'Clidinio bromuro',
					'Clindamicina' => 'Clindamicina',
					'Clobazam' => 'Clobazam',
					'Clobetasol propionato' => 'Clobetasol propionato',
					'Clomipramina clorhidrato' => 'Clomipramina clorhidrato',
					'Clonazepam' => 'Clonazepam',
					'Clopidogrel' => 'Clopidogrel',
					'Cloranfenicol' => 'Cloranfenicol',
					'Clordiazepóxido' => 'Clordiazepóxido',
					'Clorfenamina maleato' => 'Clorfenamina maleato',
					'Clorhexidina diclorhidrato' => 'Clorhexidina diclorhidrato',
					'Cloroquina Fosfato' => 'Cloroquina Fosfato',
					'Clortalidona' => 'Clortalidona',
					'Cloruro de Potasio' => 'Cloruro de Potasio',
					'Cloruro de Sodio' => 'Cloruro de Sodio',
					'Clotiazepam' => 'Clotiazepam',
					'Clotrimazol' => 'Clotrimazol',
					'Codeína fosfato (como Hemihidrato)' => 'Codeína fosfato (como Hemihidrato)',
					'Colchicina' => 'Colchicina',
					'Colecalciferol' => 'Colecalciferol',
					'Complejo Multivitamínico' => 'Complejo Multivitamínico',
					'Condroitina sulfato' => 'Condroitina sulfato',
					'Deltametrina' => 'Deltametrina',
					'Desloratadina' => 'Desloratadina',
					'Desogestrel' => 'Desogestrel',
					'Detalmetrina' => 'Detalmetrina',
					'Dexclorfeniramina maleato' => 'Dexclorfeniramina maleato',
					'Diazepam' => 'Diazepam',
					'Diclofenaco dietilamonio' => 'Diclofenaco dietilamonio',
					'Diclofenaco sódico' => 'Diclofenaco sódico',
					'Dienogest' => 'Dienogest',
					'Digoxina' => 'Digoxina',
					'Diltiazem Clorhidrato' => 'Diltiazem Clorhidrato',
					'Dipiridamol' => 'Dipiridamol',
					'Disulfiramo' => 'Disulfiramo',
					'Docetaxel Anhidro' => 'Docetaxel Anhidro',
					'Domperidona' => 'Domperidona',
					'Donepecilo clorhidrato' => 'Donepecilo clorhidrato',
					'Doxazosina (como mesilato)' => 'Doxazosina (como mesilato)',
					'Doxiciclina (monohidrato)' => 'Doxiciclina (monohidrato)',
					'Doxorrubicina clorhidrato' => 'Doxorrubicina clorhidrato',
					'Drospirenona' => 'Drospirenona',
					'Duloxetina' => 'Duloxetina',
					'Efavirenz' => 'Efavirenz',
					'Emtricitabina' => 'Emtricitabina',
					'Enalapril Maleato' => 'Enalapril Maleato',
					'Enoxaparina' => 'Enoxaparina',
					'Ergotamina Tartrato' => 'Ergotamina Tartrato',
					'Escitalopram (como oxalato)' => 'Escitalopram (como oxalato)',
					'Esomeprazol' => 'Esomeprazol',
					'Esomeprazol (como sal magnésica)' => 'Esomeprazol (como sal magnésica)',
					'Espironolactona' => 'Espironolactona',
					'Estradiol' => 'Estradiol',
					'Estradiol hemihidrato' => 'Estradiol hemihidrato',
					'Eszopiclona' => 'Eszopiclona',
					'Etinilestradiol' => 'Etinilestradiol',
					'Etopósido' => 'Etopósido',
					'Etoricoxib' => 'Etoricoxib',
					'Extracto seco de Echinacea Purpurea' => 'Extracto seco de Echinacea Purpurea',
					'Extracto seco de rizoma de Jengibre' => 'Extracto seco de rizoma de Jengibre',
					'Ezetimiba' => 'Ezetimiba',
					'Famotidina' => 'Famotidina',
					'Fenitoína sódica' => 'Fenitoína sódica',
					'Fenobarbital' => 'Fenobarbital',
					'Fenofibrato' => 'Fenofibrato',
					'Fentanilo (como citrato)' => 'Fentanilo (como citrato)',
					'Fentermina Clorhidrato' => 'Fentermina Clorhidrato',
					'Fexofenadína Clorhidrato' => 'Fexofenadína Clorhidrato',
					'Filgrastim' => 'Filgrastim',
					'Flavoxato Clorhidrato' => 'Flavoxato Clorhidrato',
					'Fluconazol' => 'Fluconazol',
					'Flunitrazepam' => 'Flunitrazepam',
					'Fluoxetina (como clorhidrato)' => 'Fluoxetina (como clorhidrato)',
					'Fluoxetina clorhidrato' => 'Fluoxetina clorhidrato',
					'Fluticasona Propionato' => 'Fluticasona Propionato',
					'Formoterol fumarato dihidrato' => 'Formoterol fumarato dihidrato',
					'Fumarato' => 'Fumarato',
					'Fumarato Ferroso' => 'Fumarato Ferroso',
					'Furazolidona' => 'Furazolidona',
					'Furosemida' => 'Furosemida',
					'Gel de hidróxido de aluminio' => 'Gel de hidróxido de aluminio',
					'Gemcitabina' => 'Gemcitabina',
					'Gemfibrozilo' => 'Gemfibrozilo',
					'Gentamicina (como sulfato)' => 'Gentamicina (como sulfato)',
					'Gestodeno' => 'Gestodeno',
					'Glibenclamida' => 'Glibenclamida',
					'Glucosa Anhidra' => 'Glucosa Anhidra',
					'Glucosamina sulfato' => 'Glucosamina sulfato',
					'Glucosamina sulfato (como sal sódica)' => 'Glucosamina sulfato (como sal sódica)',
					'Hedera Helix' => 'Hedera Helix',
					'Hidralazina Clorhidrato' => 'Hidralazina Clorhidrato',
					'Hidroclorotiazida' => 'Hidroclorotiazida',
					'Hidrocortisona' => 'Hidrocortisona',
					'Ibuprofeno' => 'Ibuprofeno',
					'Ibuprofeno (como lisinato)' => 'Ibuprofeno (como lisinato)',
					'Ifosfamida' => 'Ifosfamida',
					'Imatinib' => 'Imatinib',
					'Imipenem Monohidrato' => 'Imipenem Monohidrato',
					'Imipramina Clorhidrato' => 'Imipramina Clorhidrato',
					'Irinotecan Clorhidrato Trihidrato' => 'Irinotecan Clorhidrato Trihidrato',
					'Isotretinoína' => 'Isotretinoína',
					'Itraconazol' => 'Itraconazol',
					'Ketoconazol' => 'Ketoconazol',
					'Ketoprofeno' => 'Ketoprofeno',
					'Ketorolaco Trometamol' => 'Ketorolaco Trometamol',
					'Lactobacillus casei variedad rhamnosus' => 'Lactobacillus casei variedad rhamnosus',
					'Lactobacillus plantarum CECT 7484 1x109 UFC' => 'Lactobacillus plantarum CECT 7484 1x109 UFC',
					'Lactobacillus plantarum CECT 7485 1x109 UFC' => 'Lactobacillus plantarum CECT 7485 1x109 UFC',
					'Lactosa Monohidrato' => 'Lactosa Monohidrato',
					'Lamotrigina' => 'Lamotrigina',
					'Lansoprazol' => 'Lansoprazol',
					'Levocetirizina diclorhidrato' => 'Levocetirizina diclorhidrato',
					'Levodopa' => 'Levodopa',
					'Levodropropizina' => 'Levodropropizina',
					'Levofloxacino (como hemihidrato)' => 'Levofloxacino (como hemihidrato)',
					'Levonorgestrel' => 'Levonorgestrel',
					'Levotiroxina Sódica' => 'Levotiroxina Sódica',
					'Lidocaína' => 'Lidocaína',
					'Lidocaína Clorhidrato' => 'Lidocaína Clorhidrato',
					'Lipegfilgrastim' => 'Lipegfilgrastim',
					'Lisinopril (como dihidrato)' => 'Lisinopril (como dihidrato)',
					'Loperamida Clorhidrato' => 'Loperamida Clorhidrato',
					'Loratadina' => 'Loratadina',
					'Lorazepam' => 'Lorazepam',
					'Losartán potásico' => 'Losartán potásico',
					'Lovastatina' => 'Lovastatina',
					'Manitol' => 'Manitol',
					'Mebendazol' => 'Mebendazol',
					'Meloxicam' => 'Meloxicam',
					'Mentol' => 'Mentol',
					'Meropenem' => 'Meropenem',
					'Metamizol Sódico Monohidrato' => 'Metamizol Sódico Monohidrato',
					'Metformina Clorhidrato' => 'Metformina Clorhidrato',
					'Metildopa' => 'Metildopa',
					'Metilfenidato Clorhidrato' => 'Metilfenidato Clorhidrato',
					'Metoclopramida clorhidrato' => 'Metoclopramida clorhidrato',
					'Metotrexato' => 'Metotrexato',
					'Metronidazol' => 'Metronidazol',
					'Micofenolato mofetilo' => 'Micofenolato mofetilo',
					'Miconazol' => 'Miconazol',
					'Miconazol (como nitrato)' => 'Miconazol (como nitrato)',
					'Modafinilo' => 'Modafinilo',
					'Mometasona Furoato' => 'Mometasona Furoato',
					'Montelukast (como sal sódica)' => 'Montelukast (como sal sódica)',
					'Moxifloxacino (como Clorhidrato)' => 'Moxifloxacino (como Clorhidrato)',
					'Mupirocina' => 'Mupirocina',
					'Nafazolina clorhidrato' => 'Nafazolina clorhidrato',
					'Naproxeno sódico' => 'Naproxeno sódico',
					'Naratriptán (como clorhidrato)' => 'Naratriptán (como clorhidrato)',
					'Nebivolol' => 'Nebivolol',
					'Neomicina' => 'Neomicina',
					'Neomicina (como sulfato)' => 'Neomicina (como sulfato)',
					'Nicergolina' => 'Nicergolina',
					'Nifedipino' => 'Nifedipino',
					'Nimesulida' => 'Nimesulida',
					'Nistatina' => 'Nistatina',
					'Nitrofurantoína' => 'Nitrofurantoína',
					'Nitrofurantoína anhidra' => 'Nitrofurantoína anhidra',
					'Nitroglicerina' => 'Nitroglicerina',
					'Nomegestrol acetato' => 'Nomegestrol acetato',
					'Norepinefrina' => 'Norepinefrina',
					'Norepinetrina' => 'Norepinetrina',
					'Olanzapina' => 'Olanzapina',
					'Omeprazol' => 'Omeprazol',
					'Orlistat' => 'Orlistat',
					'Oxaliplatino' => 'Oxaliplatino',
					'Oxolamina (como citrato)' => 'Oxolamina (como citrato)',
					'Oxolamina (como fosfato)' => 'Oxolamina (como fosfato)',
					'Paclitaxel' => 'Paclitaxel',
					'Papaverina clorhidrato' => 'Papaverina clorhidrato',
					'Paracetamol' => 'Paracetamol',
					'Paracetamol (acetaminofeno)' => 'Paracetamol (acetaminofeno)',
					'Paroxetina (como Clorhidrato Hemihidrato)' => 'Paroxetina (como Clorhidrato Hemihidrato)',
					'Pediococcus acidilacti CECT 7483 1x109 UFC' => 'Pediococcus acidilacti CECT 7483 1x109 UFC',
					'Pentoxifilina' => 'Pentoxifilina',
					'Peptan' => 'Peptan',
					'Piperacilina' => 'Piperacilina',
					'Piperonil butóxido' => 'Piperonil butóxido',
					'Piridoxina clorhidrato' => 'Piridoxina clorhidrato',
					'Piritinol diclorhidrato' => 'Piritinol diclorhidrato',
					'Piroxicam' => 'Piroxicam',
					'Potasio gluconato' => 'Potasio gluconato',
					'Pramipexol diclorhidrato monohidrato' => 'Pramipexol diclorhidrato monohidrato',
					'Pramipexol diclorhidrato monohidrato (equivalente a 0,26 de Pramipexol)' => 'Pramipexol diclorhidrato monohidrato (equivalente a 0,26 de Pramipexol)',
					'Pramipexol diclorhidrato monohidrato (equivalente a 0,52 de Pramipexol)' => 'Pramipexol diclorhidrato monohidrato (equivalente a 0,52 de Pramipexol)',
					'Pramipexol diclorhidrato monohidrato (equivalente a 1,05 de Pramipexol)' => 'Pramipexol diclorhidrato monohidrato (equivalente a 1,05 de Pramipexol)',
					'Prednisona' => 'Prednisona',
					'Pregabalina' => 'Pregabalina',
					'Primidona' => 'Primidona',
					'Promestrieno' => 'Promestrieno',
					'Propranolol clorhidrato' => 'Propranolol clorhidrato',
					'Pseudoefedrina clorhidrato' => 'Pseudoefedrina clorhidrato',
					'Pseudoefedrina sulfato' => 'Pseudoefedrina sulfato',
					'Psyllium' => 'Psyllium',
					'Quetiapina (Quetiapina Fumarato)' => 'Quetiapina (Quetiapina Fumarato)',
					'Ranitidina Clorhidrato' => 'Ranitidina Clorhidrato',
					'Reslizumab' => 'Reslizumab',
					'Risperidona' => 'Risperidona',
					'Rosuvastatina (como rosuvastatina cálcica)' => 'Rosuvastatina (como rosuvastatina cálcica)',
					'Rosuvastatina (como sal cálcica)' => 'Rosuvastatina (como sal cálcica)',
					'Sacarosa' => 'Sacarosa',
					'Salbutamol (como sulfato)' => 'Salbutamol (como sulfato)',
					'Salmeterol (como Xinafoato)' => 'Salmeterol (como Xinafoato)',
					'Sertralina (como clorhidrato)' => 'Sertralina (como clorhidrato)',
					'Sildenafil (como citrato)' => 'Sildenafil (como citrato)',
					'Sulfato Ferroso' => 'Sulfato Ferroso',
					'Sulfato de bleomicina' => 'Sulfato de bleomicina',
					'Tacrolimus' => 'Tacrolimus',
					'Tadalafilo' => 'Tadalafilo',
					'Tamsulosina Clorhidrato' => 'Tamsulosina Clorhidrato',
					'Tazobactam' => 'Tazobactam',
					'Telmisartán' => 'Telmisartán',
					'Tenofovir disoproxil fumarato' => 'Tenofovir disoproxil fumarato',
					'Terbinafina (como clorhidrato)' => 'Terbinafina (como clorhidrato)',
					'Terbinafina Clorhidrato' => 'Terbinafina Clorhidrato',
					'Tetraciclina Clorhidrato' => 'Tetraciclina Clorhidrato',
					'Tiamina Clorhidrato' => 'Tiamina Clorhidrato',
					'Tibolona' => 'Tibolona',
					'Timolol (como maleato)' => 'Timolol (como maleato)',
					'Tinidazol' => 'Tinidazol',
					'Tioridazina clorhidrato' => 'Tioridazina clorhidrato',
					'Tiotropio' => 'Tiotropio',
					'Tiotropio (como Bromuro de Tiotropio)' => 'Tiotropio (como Bromuro de Tiotropio)',
					'Tolnaftato' => 'Tolnaftato',
					'Tramadol clorhidrato' => 'Tramadol clorhidrato',
					'Trazodona clorhidrato' => 'Trazodona clorhidrato',
					'Triamtereno' => 'Triamtereno',
					'Trihexifenidilo clorhidrato' => 'Trihexifenidilo clorhidrato',
					'Valganciclovir (como clorhidrato)' => 'Valganciclovir (como clorhidrato)',
					'Valsartán' => 'Valsartán',
					'Vancomicina' => 'Vancomicina',
					'Vaselina líquida medicinal' => 'Vaselina líquida medicinal',
					'Venlafaxina (como clorhidrato)' => 'Venlafaxina (como clorhidrato)',
					'Vinblastina Sulfato' => 'Vinblastina Sulfato',
					'Vitamina A' => 'Vitamina A',
					'Vitamina C' => 'Vitamina C',
					'Vitamina D3' => 'Vitamina D3',
					'Ácido Alendrónico' => 'Ácido Alendrónico',
					'Ácido Ascórbico' => 'Ácido Ascórbico',
					'Ácido Clavulánico (como sal potásica)' => 'Ácido Clavulánico (como sal potásica)',
					'Ácido Fólico' => 'Ácido Fólico',
					'Ácido Ibandrónico (como Ibandronato Sódico Monohidrato)' => 'Ácido Ibandrónico (como Ibandronato Sódico Monohidrato)',
					'Ácido Mefenámico' => 'Ácido Mefenámico',
					'Ácido clavulánico' => 'Ácido clavulánico',
					'Óxido de zinc' => 'Óxido de zinc',
				),
				'default_value' => array(),
				'return_format' => 'value',
				'multiple' => 1,
				'allow_null' => 1,
				'ui' => 1,
				'ajax' => 1,
				'placeholder' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'acf-options',
				),
			),
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'producto',
				),
			),
		),
		'menu_order' => -3,
		'position' => 'acf_after_title',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
		'show_in_rest' => 0,
	));

	acf_add_local_field_group(array(
		'key' => 'group_5b8993b0c369c',
		'title' => 'SKU',
		'fields' => array(
			array(
				'key' => 'field_5b8993b50683a',
				'label' => 'SKU Lab',
				'name' => 'sku_lab',
				'aria-label' => '',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5b8993dd0683b',
				'label' => 'SKU Farmacias',
				'name' => 'sku_farmacias',
				'aria-label' => '',
				'type' => 'repeater',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'collapsed' => '',
				'min' => 0,
				'max' => 0,
				'layout' => 'table',
				'button_label' => 'Agregar Fila',
				'rows_per_page' => 20,
				'sub_fields' => array(
					array(
						'key' => 'field_5b8993f70683c',
						'label' => 'cadena',
						'name' => 'cadena',
						'aria-label' => '',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
						'parent_repeater' => 'field_5b8993dd0683b',
					),
					array(
						'key' => 'field_5b89943cd7594',
						'label' => 'sku',
						'name' => 'sku',
						'aria-label' => '',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
						'parent_repeater' => 'field_5b8993dd0683b',
					),
					array(
						'key' => 'field_5b899485d8a1e',
						'label' => 'nombre producto en clinica',
						'name' => 'nombre_producto_en_clinica',
						'aria-label' => '',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
						'parent_repeater' => 'field_5b8993dd0683b',
					),
					array(
						'key' => 'field_5b899499d8a1f',
						'label' => 'nombre laboratorio',
						'name' => 'nombre_laboratorio',
						'aria-label' => '',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
						'parent_repeater' => 'field_5b8993dd0683b',
					),
					array(
						'key' => 'field_5b8994a1d8a20',
						'label' => 'sku laboratorio',
						'name' => 'sku_laboratorio',
						'aria-label' => '',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
						'parent_repeater' => 'field_5b8993dd0683b',
					),
				),
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'producto',
				),
			),
		),
		'menu_order' => -3,
		'position' => 'acf_after_title',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
		'show_in_rest' => false,
		'modified' => 1606768610,
	));

	acf_add_local_field_group(array(
		'key' => 'group_55c235d9897a2',
		'title' => 'Ficha producto',
		'fields' => array(
			array(
				'key' => 'field_5fc69cf2fa075',
				'label' => 'Campaña asociada',
				'name' => 'campana_asociada',
				'aria-label' => '',
				'type' => 'link',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'array',
			),
			array(
				'key' => 'field_5ce2da6da6fdd',
				'label' => 'Ficha por defecto',
				'name' => 'ficha_por_defecto',
				'aria-label' => '',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					-1 => 'Todos',
				),
				'default_value' => -1,
				'allow_null' => 1,
				'multiple' => 0,
				'ui' => 0,
				'return_format' => 'value',
				'ajax' => 0,
				'placeholder' => '',
			),
			array(
				'key' => 'field_5cbde10e5a08f',
				'label' => 'Links a e-commerce',
				'name' => 'farmacias',
				'aria-label' => '',
				'type' => 'repeater',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'collapsed' => '',
				'min' => 0,
				'max' => 0,
				'layout' => 'table',
				'button_label' => 'Agregar Farmacia',
				'rows_per_page' => 20,
				'sub_fields' => array(
					array(
						'key' => 'field_5cc7042ee9c2a',
						'label' => 'Url Farmacia',
						'name' => 'url_farmacia',
						'aria-label' => '',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
						'parent_repeater' => 'field_5cbde10e5a08f',
					),
					array(
						'key' => 'field_5cdf054562062',
						'label' => 'Farmacia',
						'name' => 'farmacia',
						'aria-label' => '',
						'type' => 'select',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							'fz' => 'Farmazon',
							'fx' => 'Farmex',
							'ph' => 'Pharol',
							'ec' => 'Farmacia Económica',
							'ah' => 'Ahumada',
							'cv' => 'CruzVerde',
							'fr' => 'Fracción',
							'sb' => 'Salcobrand',
							'remedia' => 'Remedia',
							'belgo' => 'Farmacia Belgochilena',
							'rfarma' => 'Redfarma',
							'tfarma' => 'TodoFarma',
							'farmam' => 'Farmam',
							'simi' => 'Simi',
							'meddica' => 'Farmacia Meddica',
							'ml' => 'Mercado Libre',
							'cofar' => 'Cofar',
							'eco' => 'EcoFarmacias',
							'asfar' => 'Asfar Farmacia',
							'liga-ep' => 'Liga Chile contra la Epilepsia',
							'profar' => 'Profar',
						),
						'default_value' => false,
						'allow_null' => 0,
						'multiple' => 0,
						'ui' => 1,
						'ajax' => 0,
						'return_format' => 'value',
						'placeholder' => '',
						'parent_repeater' => 'field_5cbde10e5a08f',
					),
					array(
						'key' => 'field_5cc7043de9c2b',
						'label' => 'Tipo de producto',
						'name' => 'tipo_de_producto',
						'aria-label' => '',
						'type' => 'select',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							-1 => 'Todos',
						),
						'default_value' => array(
							0 => -1,
						),
						'allow_null' => 0,
						'multiple' => 1,
						'ui' => 0,
						'return_format' => 'value',
						'ajax' => 0,
						'placeholder' => '',
						'parent_repeater' => 'field_5cbde10e5a08f',
					),
					array(
						'key' => 'field_605dd023f1ca6',
						'label' => 'Fijar posición',
						'name' => 'fijar_posicion',
						'aria-label' => '',
						'type' => 'true_false',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'message' => '',
						'default_value' => 0,
						'ui' => 1,
						'ui_on_text' => '',
						'ui_off_text' => '',
						'parent_repeater' => 'field_5cbde10e5a08f',
					),
				),
			),
			array(
				'key' => 'field_55c235df11f5b',
				'label' => 'Slider producto',
				'name' => 'slider_producto',
				'aria-label' => '',
				'type' => 'repeater',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'collapsed' => '',
				'min' => 0,
				'max' => 0,
				'layout' => 'row',
				'button_label' => 'Add Row',
				'rows_per_page' => 20,
				'sub_fields' => array(
					array(
						'key' => 'field_62e7d9c2360d7',
						'label' => 'Tipo de contenido',
						'name' => 'tipo',
						'aria-label' => '',
						'type' => 'select',
						'instructions' => '',
						'required' => 1,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							'img' => 'Imagen',
							'yt' => 'YouTube',
							360 => 'Vista 360',
						),
						'default_value' => 'img',
						'allow_null' => 0,
						'multiple' => 0,
						'ui' => 0,
						'return_format' => 'value',
						'ajax' => 0,
						'placeholder' => '',
						'parent_repeater' => 'field_55c235df11f5b',
					),
					array(
						'key' => 'field_55c235ee11f5c',
						'label' => 'Imagen',
						'name' => 'imagen',
						'aria-label' => '',
						'type' => 'image',
						'instructions' => '',
						'required' => 1,
						'conditional_logic' => array(
							array(
								array(
									'field' => 'field_62e7d9c2360d7',
									'operator' => '==',
									'value' => 'img',
								),
							),
						),
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'return_format' => 'array',
						'preview_size' => 'thumbnail',
						'library' => 'all',
						'min_width' => '',
						'min_height' => '',
						'min_size' => '',
						'max_width' => '',
						'max_height' => '',
						'max_size' => '',
						'mime_types' => '',
						'parent_repeater' => 'field_55c235df11f5b',
					),
					array(
						'key' => 'field_5b901c7df35a9',
						'label' => 'Tipo de producto',
						'name' => 'tipo_de_producto',
						'aria-label' => '',
						'type' => 'select',
						'instructions' => '',
						'required' => 1,
						'conditional_logic' => array(
							array(
								array(
									'field' => 'field_62e7d9c2360d7',
									'operator' => '==',
									'value' => 'img',
								),
							),
						),
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							-1 => 'Todos',
						),
						'default_value' => array(
							0 => -1,
						),
						'allow_null' => 0,
						'multiple' => 1,
						'ui' => 0,
						'return_format' => 'value',
						'ajax' => 0,
						'placeholder' => '',
						'parent_repeater' => 'field_55c235df11f5b',
					),
					array(
						'key' => 'field_62e7da79360d8',
						'label' => 'Vista 360',
						'name' => 'vista',
						'aria-label' => '',
						'type' => 'url',
						'instructions' => '',
						'required' => 1,
						'conditional_logic' => array(
							array(
								array(
									'field' => 'field_62e7d9c2360d7',
									'operator' => '==',
									'value' => '360',
								),
							),
						),
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'parent_repeater' => 'field_55c235df11f5b',
					),
					array(
						'key' => 'field_62e7da94360d9',
						'label' => 'Video',
						'name' => 'video',
						'aria-label' => '',
						'type' => 'oembed',
						'instructions' => '',
						'required' => 1,
						'conditional_logic' => array(
							array(
								array(
									'field' => 'field_62e7d9c2360d7',
									'operator' => '==',
									'value' => 'yt',
								),
							),
						),
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'width' => '',
						'height' => '',
						'parent_repeater' => 'field_55c235df11f5b',
					),
					array(
						'key' => 'field_62e7ddbe19040',
						'label' => 'Miniatura',
						'name' => 'miniatura',
						'aria-label' => '',
						'type' => 'image',
						'instructions' => '',
						'required' => 1,
						'conditional_logic' => array(
							array(
								array(
									'field' => 'field_62e7d9c2360d7',
									'operator' => '!=',
									'value' => 'img',
								),
							),
						),
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'return_format' => 'array',
						'preview_size' => 'thumbnail',
						'library' => 'all',
						'min_width' => '',
						'min_height' => '',
						'min_size' => '',
						'max_width' => '',
						'max_height' => '',
						'max_size' => '',
						'mime_types' => '',
						'parent_repeater' => 'field_55c235df11f5b',
					),
				),
			),
			array(
				'key' => 'field_55c25a8321f05',
				'label' => 'Composición',
				'name' => 'composicion',
				'aria-label' => '',
				'type' => 'wysiwyg',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'tabs' => 'all',
				'toolbar' => 'full',
				'media_upload' => 1,
				'delay' => 0,
			),
			array(
				'key' => 'field_5b9019ec1d339',
				'label' => 'Composición',
				'name' => 'composicion_repeater',
				'aria-label' => '',
				'type' => 'repeater',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'collapsed' => '',
				'min' => 0,
				'max' => 0,
				'layout' => 'row',
				'button_label' => 'Agregar Fila',
				'rows_per_page' => 20,
				'sub_fields' => array(
					array(
						'key' => 'field_5b901a081d33a',
						'label' => 'Tipo de Producto',
						'name' => 'tipo_de_producto',
						'aria-label' => '',
						'type' => 'select',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							-1 => 'Todos',
						),
						'default_value' => array(
							0 => -1,
						),
						'allow_null' => 0,
						'multiple' => 1,
						'ui' => 0,
						'return_format' => 'value',
						'ajax' => 0,
						'placeholder' => '',
						'parent_repeater' => 'field_5b9019ec1d339',
					),
					array(
						'key' => 'field_5b901a4a1d33b',
						'label' => 'composición',
						'name' => 'composicion',
						'aria-label' => '',
						'type' => 'wysiwyg',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'tabs' => 'all',
						'toolbar' => 'full',
						'media_upload' => 1,
						'delay' => 0,
						'parent_repeater' => 'field_5b9019ec1d339',
					),
				),
			),
			array(
				'key' => 'field_55c25ae621f06',
				'label' => 'Advertencia de lectura',
				'name' => 'advertencia_de_lectura',
				'aria-label' => '',
				'type' => 'wysiwyg',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'tabs' => 'all',
				'toolbar' => 'full',
				'media_upload' => 1,
				'delay' => 0,
			),
			array(
				'key' => 'field_5b901c20f35a6',
				'label' => 'Advertencia de lectura',
				'name' => 'advertencia_de_lectura_repeater',
				'aria-label' => '',
				'type' => 'repeater',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'collapsed' => '',
				'min' => 0,
				'max' => 0,
				'layout' => 'row',
				'button_label' => 'Agregar Fila',
				'rows_per_page' => 20,
				'sub_fields' => array(
					array(
						'key' => 'field_5b901c39f35a7',
						'label' => 'Tipo de producto',
						'name' => 'tipo_de_producto',
						'aria-label' => '',
						'type' => 'select',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							-1 => 'Todos',
						),
						'default_value' => array(
							0 => -1,
						),
						'allow_null' => 0,
						'multiple' => 1,
						'ui' => 0,
						'return_format' => 'value',
						'ajax' => 0,
						'placeholder' => '',
						'parent_repeater' => 'field_5b901c20f35a6',
					),
					array(
						'key' => 'field_5b901c3cf35a8',
						'label' => 'Advertencia de lectura',
						'name' => 'advertencia_de_lectura',
						'aria-label' => '',
						'type' => 'wysiwyg',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'tabs' => 'all',
						'toolbar' => 'full',
						'media_upload' => 1,
						'delay' => 0,
						'parent_repeater' => 'field_5b901c20f35a6',
					),
				),
			),
			array(
				'key' => 'field_55c4f0792bb81',
				'label' => 'Importante',
				'name' => 'importante',
				'aria-label' => '',
				'type' => 'wysiwyg',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'tabs' => 'all',
				'toolbar' => 'full',
				'media_upload' => 1,
				'delay' => 0,
			),
			array(
				'key' => 'field_5b901ca6f35aa',
				'label' => 'Importante',
				'name' => 'importante_repeater',
				'aria-label' => '',
				'type' => 'repeater',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'collapsed' => '',
				'min' => 0,
				'max' => 0,
				'layout' => 'row',
				'button_label' => 'Agregar Fila',
				'rows_per_page' => 20,
				'sub_fields' => array(
					array(
						'key' => 'field_5b901cb4f35ab',
						'label' => 'Tipo de producto',
						'name' => 'tipo_de_producto',
						'aria-label' => '',
						'type' => 'select',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							-1 => 'Todos',
						),
						'default_value' => array(
							0 => -1,
						),
						'allow_null' => 0,
						'multiple' => 1,
						'ui' => 0,
						'return_format' => 'value',
						'ajax' => 0,
						'placeholder' => '',
						'parent_repeater' => 'field_5b901ca6f35aa',
					),
					array(
						'key' => 'field_5b901cc3f35ac',
						'label' => 'Importante',
						'name' => 'importante',
						'aria-label' => '',
						'type' => 'wysiwyg',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'tabs' => 'all',
						'toolbar' => 'full',
						'media_upload' => 1,
						'delay' => 0,
						'parent_repeater' => 'field_5b901ca6f35aa',
					),
				),
			),
			array(
				'key' => 'field_55c25703ab371',
				'label' => 'Contenidos',
				'name' => 'contenidos',
				'aria-label' => '',
				'type' => 'repeater',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'min' => 0,
				'max' => 0,
				'layout' => 'row',
				'button_label' => 'Add Row',
				'collapsed' => '',
				'rows_per_page' => 20,
				'sub_fields' => array(
					array(
						'key' => 'field_55c2570eab372',
						'label' => 'Título',
						'name' => 'titulo',
						'aria-label' => '',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
						'readonly' => 0,
						'disabled' => 0,
						'parent_repeater' => 'field_55c25703ab371',
					),
					array(
						'key' => 'field_5b8ff0cee5d1f',
						'label' => 'Tipo de Producto',
						'name' => 'tipo_de_producto',
						'aria-label' => '',
						'type' => 'select',
						'instructions' => '',
						'required' => 1,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							-1 => 'Todos',
						),
						'default_value' => array(
							0 => -1,
						),
						'allow_null' => 0,
						'multiple' => 1,
						'ui' => 0,
						'return_format' => 'value',
						'ajax' => 0,
						'placeholder' => '',
						'parent_repeater' => 'field_55c25703ab371',
					),
					array(
						'key' => 'field_55c25e401224a',
						'label' => 'Tipo texto',
						'name' => 'tipo_texto',
						'aria-label' => '',
						'type' => 'select',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							'simple-baja' => 'simple-baja',
							'simple-alta' => 'simple-alta',
							'lista-baja' => 'lista-baja',
							'lista-alta' => 'lista-alta',
						),
						'default_value' => false,
						'allow_null' => 0,
						'multiple' => 0,
						'ui' => 0,
						'ajax' => 0,
						'placeholder' => '',
						'disabled' => 0,
						'readonly' => 0,
						'return_format' => 'value',
						'parent_repeater' => 'field_55c25703ab371',
					),
					array(
						'key' => 'field_55c25a6aab374',
						'label' => 'Contenido',
						'name' => 'contenido',
						'aria-label' => '',
						'type' => 'wysiwyg',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => array(
							array(
								array(
									'field' => 'field_55c25e401224a',
									'operator' => '==',
									'value' => 'simple-baja',
								),
							),
							array(
								array(
									'field' => 'field_55c25e401224a',
									'operator' => '==',
									'value' => 'simple-alta',
								),
							),
						),
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'tabs' => 'all',
						'toolbar' => 'full',
						'media_upload' => 1,
						'delay' => 0,
						'parent_repeater' => 'field_55c25703ab371',
					),
					array(
						'key' => 'field_55c25eca1224b',
						'label' => 'Listado',
						'name' => 'listado',
						'aria-label' => '',
						'type' => 'repeater',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => array(
							array(
								array(
									'field' => 'field_55c25e401224a',
									'operator' => '==',
									'value' => 'lista-baja',
								),
							),
							array(
								array(
									'field' => 'field_55c25e401224a',
									'operator' => '==',
									'value' => 'lista-alta',
								),
							),
						),
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'min' => 0,
						'max' => 0,
						'layout' => 'table',
						'button_label' => 'Add Row',
						'collapsed' => '',
						'rows_per_page' => 20,
						'sub_fields' => array(
							array(
								'key' => 'field_55c25f001224d',
								'label' => 'Item',
								'name' => 'item',
								'aria-label' => '',
								'type' => 'wysiwyg',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'tabs' => 'all',
								'toolbar' => 'full',
								'media_upload' => 0,
								'delay' => 0,
								'parent_repeater' => 'field_55c25eca1224b',
							),
						),
						'parent_repeater' => 'field_55c25703ab371',
					),
					array(
						'key' => 'field_55c2571bab373',
						'label' => 'Color',
						'name' => 'color',
						'aria-label' => '',
						'type' => 'select',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							'azul' => 'azul',
							'rojo' => 'rojo',
						),
						'default_value' => false,
						'allow_null' => 1,
						'multiple' => 0,
						'ui' => 0,
						'ajax' => 0,
						'placeholder' => '',
						'disabled' => 0,
						'readonly' => 0,
						'return_format' => 'value',
						'parent_repeater' => 'field_55c25703ab371',
					),
				),
			),
			array(
				'key' => 'field_55cdda1c8055f',
				'label' => 'Convenio ges',
				'name' => 'convenio_ges',
				'aria-label' => '',
				'type' => 'repeater',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'collapsed' => '',
				'min' => 0,
				'max' => 0,
				'layout' => 'row',
				'button_label' => 'Add Row',
				'rows_per_page' => 20,
				'sub_fields' => array(
					array(
						'key' => 'field_55cdda5b80560',
						'label' => 'Isapre',
						'name' => 'isapre',
						'aria-label' => '',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
						'readonly' => 0,
						'disabled' => 0,
						'parent_repeater' => 'field_55cdda1c8055f',
					),
					array(
						'key' => 'field_55cdda6280561',
						'label' => 'Farmacia',
						'name' => 'farmacia',
						'aria-label' => '',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
						'readonly' => 0,
						'disabled' => 0,
						'parent_repeater' => 'field_55cdda1c8055f',
					),
					array(
						'key' => 'field_5b901ce1f35ad',
						'label' => 'Tipo de producto',
						'name' => 'tipo_de_producto',
						'aria-label' => '',
						'type' => 'select',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							-1 => 'Todos',
						),
						'default_value' => array(
							0 => -1,
						),
						'allow_null' => 0,
						'multiple' => 1,
						'ui' => 0,
						'return_format' => 'value',
						'ajax' => 0,
						'placeholder' => '',
						'parent_repeater' => 'field_55cdda1c8055f',
					),
				),
			),
			array(
				'key' => 'field_55ce0f96b52c8',
				'label' => 'Folleto PDF',
				'name' => 'descargable',
				'aria-label' => '',
				'type' => 'file',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'array',
				'library' => 'all',
				'min_size' => '',
				'max_size' => '',
				'mime_types' => '',
			),
			array(
				'key' => 'field_5fc6957e1db99',
				'label' => 'Folleto Audio',
				'name' => 'descargable_audio',
				'aria-label' => '',
				'type' => 'file',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'array',
				'library' => 'all',
				'min_size' => '',
				'max_size' => '',
				'mime_types' => 'mp3,MP3',
			),
			array(
				'key' => 'field_576944bab0bd9',
				'label' => 'Principio activo y concentración',
				'name' => 'principio_activo_y_concentracion',
				'aria-label' => '',
				'type' => 'repeater',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'collapsed' => '',
				'min' => 0,
				'max' => 0,
				'layout' => 'table',
				'button_label' => 'Agregar Fila',
				'rows_per_page' => 20,
				'sub_fields' => array(
					array(
						'key' => 'field_5b901d0af35ae',
						'label' => 'Tipo de producto',
						'name' => 'tipo_de_producto',
						'aria-label' => '',
						'type' => 'select',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							-1 => 'Todos',
						),
						'default_value' => array(
							0 => -1,
						),
						'allow_null' => 0,
						'multiple' => 1,
						'ui' => 0,
						'return_format' => 'value',
						'ajax' => 0,
						'placeholder' => '',
						'parent_repeater' => 'field_576944bab0bd9',
					),
					array(
						'key' => 'field_576944c2b0bda',
						'label' => 'Principio activo',
						'name' => 'principio_activo',
						'aria-label' => '',
						'type' => 'select',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							'Aceite de Eucalipto' => 'Aceite de Eucalipto',
							'Acetato de Glatiramer' => 'Acetato de Glatiramer',
							'Acetato de ciproterona' => 'Acetato de ciproterona',
							'Acetazolamida' => 'Acetazolamida',
							'Aciclovir' => 'Aciclovir',
							'Alcanfor' => 'Alcanfor',
							'Alcohol polivinílico' => 'Alcohol polivinílico',
							'Almidón de Maíz' => 'Almidón de Maíz',
							'Alprazolam' => 'Alprazolam',
							'Amikacina (como sulfato)' => 'Amikacina (como sulfato)',
							'Amitriptilina clorhidrato' => 'Amitriptilina clorhidrato',
							'Amlodipino (como besilato)' => 'Amlodipino (como besilato)',
							'Amoxicilina' => 'Amoxicilina',
							'Amoxicilina (como trihidrato)' => 'Amoxicilina (como trihidrato)',
							'Anfebutamona Clorhidrato (Bupropión)' => 'Anfebutamona Clorhidrato (Bupropión)',
							'Anfepramona clorhidrato' => 'Anfepramona clorhidrato',
							'Armodafinilo' => 'Armodafinilo',
							'Atazanavir' => 'Atazanavir',
							'Atenolol' => 'Atenolol',
							'Atorvastatina (como Atorvastatina Cálcica forma I Trihidrato)' => 'Atorvastatina (como Atorvastatina Cálcica forma I Trihidrato)',
							'Atorvastatina (como Atorvastatina cálcica cristalina forma VIII)' => 'Atorvastatina (como Atorvastatina cálcica cristalina forma VIII)',
							'Atropina sulfato' => 'Atropina sulfato',
							'Azitromicina' => 'Azitromicina',
							'Azitromicina (como dihidrato)' => 'Azitromicina (como dihidrato)',
							'Bacitracina' => 'Bacitracina',
							'Balitarían' => 'Balitarían',
							'Beclometasona dipropionato' => 'Beclometasona dipropionato',
							'Bendamustina Clorhidrato' => 'Bendamustina Clorhidrato',
							'Benserazida clorhidrato' => 'Benserazida clorhidrato',
							'Betametasona' => 'Betametasona',
							'Betametasona (como Dipropionato)' => 'Betametasona (como Dipropionato)',
							'Betametasona Acetato Micronizada' => 'Betametasona Acetato Micronizada',
							'Betametasona Sodio Fosfato' => 'Betametasona Sodio Fosfato',
							'Betametosona Acetato Micronizada' => 'Betametosona Acetato Micronizada',
							'Betaxolol (como clorhidrato)' => 'Betaxolol (como clorhidrato)',
							'Bisoprolol Fumarato' => 'Bisoprolol Fumarato',
							'Bortezomib' => 'Bortezomib',
							'Bromazepam' => 'Bromazepam',
							'Budesonida' => 'Budesonida',
							'Cafeína' => 'Cafeína',
							'Calcio (como carbonato)' => 'Calcio (como carbonato)',
							'Calcio carbonato' => 'Calcio carbonato',
							'Capecitabina' => 'Capecitabina',
							'Carbamazepina' => 'Carbamazepina',
							'Carbidopa (como monohidrato)' => 'Carbidopa (como monohidrato)',
							'Carbonato de calcio' => 'Carbonato de calcio',
							'Carvedilol' => 'Carvedilol',
							'Cefadroxilo (como monohidrato)' => 'Cefadroxilo (como monohidrato)',
							'Cefazolina' => 'Cefazolina',
							'Ceftriaxona' => 'Ceftriaxona',
							'Celecoxib' => 'Celecoxib',
							'Cetirizina diclorhidrato' => 'Cetirizina diclorhidrato',
							'Ciclobenzaprina' => 'Ciclobenzaprina',
							'Ciclobenzaprina clorhidrato' => 'Ciclobenzaprina clorhidrato',
							'Ciclosporina' => 'Ciclosporina',
							'Cilastatina Sódica' => 'Cilastatina Sódica',
							'Cinarizina' => 'Cinarizina',
							'Ciprofloxacino (como clorhidrato monohidrato)' => 'Ciprofloxacino (como clorhidrato monohidrato)',
							'Citalaprom (como bromhidrato)' => 'Citalaprom (como bromhidrato)',
							'Citalopram' => 'Citalopram',
							'Citalopram (como bromhidrato)' => 'Citalopram (como bromhidrato)',
							'Citrato de Sodio' => 'Citrato de Sodio',
							'Claritromicina' => 'Claritromicina',
							'Clidinio bromuro' => 'Clidinio bromuro',
							'Clindamicina' => 'Clindamicina',
							'Clobazam' => 'Clobazam',
							'Clobetasol propionato' => 'Clobetasol propionato',
							'Clomipramina clorhidrato' => 'Clomipramina clorhidrato',
							'Clonazepam' => 'Clonazepam',
							'Clopidogrel' => 'Clopidogrel',
							'Cloranfenicol' => 'Cloranfenicol',
							'Clordiazepóxido' => 'Clordiazepóxido',
							'Clorfenamina maleato' => 'Clorfenamina maleato',
							'Clorhexidina diclorhidrato' => 'Clorhexidina diclorhidrato',
							'Cloroquina Fosfato' => 'Cloroquina Fosfato',
							'Clortalidona' => 'Clortalidona',
							'Cloruro de Potasio' => 'Cloruro de Potasio',
							'Cloruro de Sodio' => 'Cloruro de Sodio',
							'Clotiazepam' => 'Clotiazepam',
							'Clotrimazol' => 'Clotrimazol',
							'Codeína fosfato (como Hemihidrato)' => 'Codeína fosfato (como Hemihidrato)',
							'Colchicina' => 'Colchicina',
							'Colecalciferol' => 'Colecalciferol',
							'Complejo Multivitamínico' => 'Complejo Multivitamínico',
							'Condroitina sulfato' => 'Condroitina sulfato',
							'Deltametrina' => 'Deltametrina',
							'Desloratadina' => 'Desloratadina',
							'Desogestrel' => 'Desogestrel',
							'Detalmetrina' => 'Detalmetrina',
							'Dexclorfeniramina maleato' => 'Dexclorfeniramina maleato',
							'Diazepam' => 'Diazepam',
							'Diclofenaco dietilamonio' => 'Diclofenaco dietilamonio',
							'Diclofenaco sódico' => 'Diclofenaco sódico',
							'Dienogest' => 'Dienogest',
							'Digoxina' => 'Digoxina',
							'Diltiazem Clorhidrato' => 'Diltiazem Clorhidrato',
							'Dipiridamol' => 'Dipiridamol',
							'Disulfiramo' => 'Disulfiramo',
							'Docetaxel Anhidro' => 'Docetaxel Anhidro',
							'Domperidona' => 'Domperidona',
							'Donepecilo clorhidrato' => 'Donepecilo clorhidrato',
							'Doxazosina (como mesilato)' => 'Doxazosina (como mesilato)',
							'Doxiciclina (monohidrato)' => 'Doxiciclina (monohidrato)',
							'Doxorrubicina clorhidrato' => 'Doxorrubicina clorhidrato',
							'Drospirenona' => 'Drospirenona',
							'Duloxetina' => 'Duloxetina',
							'Efavirenz' => 'Efavirenz',
							'Emtricitabina' => 'Emtricitabina',
							'Enalapril Maleato' => 'Enalapril Maleato',
							'Enoxaparina' => 'Enoxaparina',
							'Ergotamina Tartrato' => 'Ergotamina Tartrato',
							'Escitalopram (como oxalato)' => 'Escitalopram (como oxalato)',
							'Esomeprazol' => 'Esomeprazol',
							'Esomeprazol (como sal magnésica)' => 'Esomeprazol (como sal magnésica)',
							'Espironolactona' => 'Espironolactona',
							'Estradiol' => 'Estradiol',
							'Estradiol hemihidrato' => 'Estradiol hemihidrato',
							'Eszopiclona' => 'Eszopiclona',
							'Etinilestradiol' => 'Etinilestradiol',
							'Etopósido' => 'Etopósido',
							'Etoricoxib' => 'Etoricoxib',
							'Extracto seco de Echinacea Purpurea' => 'Extracto seco de Echinacea Purpurea',
							'Extracto seco de rizoma de Jengibre' => 'Extracto seco de rizoma de Jengibre',
							'Ezetimiba' => 'Ezetimiba',
							'Famotidina' => 'Famotidina',
							'Fenitoína sódica' => 'Fenitoína sódica',
							'Fenobarbital' => 'Fenobarbital',
							'Fenofibrato' => 'Fenofibrato',
							'Fentanilo (como citrato)' => 'Fentanilo (como citrato)',
							'Fentermina Clorhidrato' => 'Fentermina Clorhidrato',
							'Fexofenadína Clorhidrato' => 'Fexofenadína Clorhidrato',
							'Filgrastim' => 'Filgrastim',
							'Flavoxato Clorhidrato' => 'Flavoxato Clorhidrato',
							'Fluconazol' => 'Fluconazol',
							'Flunitrazepam' => 'Flunitrazepam',
							'Fluoxetina (como clorhidrato)' => 'Fluoxetina (como clorhidrato)',
							'Fluoxetina clorhidrato' => 'Fluoxetina clorhidrato',
							'Fluticasona Propionato' => 'Fluticasona Propionato',
							'Formoterol fumarato dihidrato' => 'Formoterol fumarato dihidrato',
							'Fumarato' => 'Fumarato',
							'Fumarato Ferroso' => 'Fumarato Ferroso',
							'Furazolidona' => 'Furazolidona',
							'Furosemida' => 'Furosemida',
							'Gel de hidróxido de aluminio' => 'Gel de hidróxido de aluminio',
							'Gemcitabina' => 'Gemcitabina',
							'Gemfibrozilo' => 'Gemfibrozilo',
							'Gentamicina (como sulfato)' => 'Gentamicina (como sulfato)',
							'Gestodeno' => 'Gestodeno',
							'Glibenclamida' => 'Glibenclamida',
							'Glucosa Anhidra' => 'Glucosa Anhidra',
							'Glucosamina sulfato' => 'Glucosamina sulfato',
							'Glucosamina sulfato (como sal sódica)' => 'Glucosamina sulfato (como sal sódica)',
							'Hedera Helix' => 'Hedera Helix',
							'Hidralazina Clorhidrato' => 'Hidralazina Clorhidrato',
							'Hidroclorotiazida' => 'Hidroclorotiazida',
							'Hidrocortisona' => 'Hidrocortisona',
							'Ibuprofeno' => 'Ibuprofeno',
							'Ibuprofeno (como lisinato)' => 'Ibuprofeno (como lisinato)',
							'Ifosfamida' => 'Ifosfamida',
							'Imatinib' => 'Imatinib',
							'Imipenem Monohidrato' => 'Imipenem Monohidrato',
							'Imipramina Clorhidrato' => 'Imipramina Clorhidrato',
							'Irinotecan Clorhidrato Trihidrato' => 'Irinotecan Clorhidrato Trihidrato',
							'Isotretinoína' => 'Isotretinoína',
							'Itraconazol' => 'Itraconazol',
							'Ketoconazol' => 'Ketoconazol',
							'Ketoprofeno' => 'Ketoprofeno',
							'Ketorolaco Trometamol' => 'Ketorolaco Trometamol',
							'Lactobacillus casei variedad rhamnosus' => 'Lactobacillus casei variedad rhamnosus',
							'Lactobacillus plantarum CECT 7484 1x109 UFC' => 'Lactobacillus plantarum CECT 7484 1x109 UFC',
							'Lactobacillus plantarum CECT 7485 1x109 UFC' => 'Lactobacillus plantarum CECT 7485 1x109 UFC',
							'Lactosa Monohidrato' => 'Lactosa Monohidrato',
							'Lamotrigina' => 'Lamotrigina',
							'Lansoprazol' => 'Lansoprazol',
							'Levocetirizina diclorhidrato' => 'Levocetirizina diclorhidrato',
							'Levodopa' => 'Levodopa',
							'Levodropropizina' => 'Levodropropizina',
							'Levofloxacino (como hemihidrato)' => 'Levofloxacino (como hemihidrato)',
							'Levonorgestrel' => 'Levonorgestrel',
							'Levotiroxina Sódica' => 'Levotiroxina Sódica',
							'Lidocaína' => 'Lidocaína',
							'Lidocaína Clorhidrato' => 'Lidocaína Clorhidrato',
							'Lipegfilgrastim' => 'Lipegfilgrastim',
							'Lisinopril (como dihidrato)' => 'Lisinopril (como dihidrato)',
							'Loperamida Clorhidrato' => 'Loperamida Clorhidrato',
							'Loratadina' => 'Loratadina',
							'Lorazepam' => 'Lorazepam',
							'Losartán potásico' => 'Losartán potásico',
							'Lovastatina' => 'Lovastatina',
							'Manitol' => 'Manitol',
							'Mebendazol' => 'Mebendazol',
							'Meloxicam' => 'Meloxicam',
							'Mentol' => 'Mentol',
							'Meropenem' => 'Meropenem',
							'Metamizol Sódico Monohidrato' => 'Metamizol Sódico Monohidrato',
							'Metformina Clorhidrato' => 'Metformina Clorhidrato',
							'Metildopa' => 'Metildopa',
							'Metilfenidato Clorhidrato' => 'Metilfenidato Clorhidrato',
							'Metoclopramida clorhidrato' => 'Metoclopramida clorhidrato',
							'Metotrexato' => 'Metotrexato',
							'Metronidazol' => 'Metronidazol',
							'Micofenolato mofetilo' => 'Micofenolato mofetilo',
							'Miconazol' => 'Miconazol',
							'Miconazol (como nitrato)' => 'Miconazol (como nitrato)',
							'Modafinilo' => 'Modafinilo',
							'Mometasona Furoato' => 'Mometasona Furoato',
							'Montelukast (como sal sódica)' => 'Montelukast (como sal sódica)',
							'Moxifloxacino (como Clorhidrato)' => 'Moxifloxacino (como Clorhidrato)',
							'Mupirocina' => 'Mupirocina',
							'Nafazolina clorhidrato' => 'Nafazolina clorhidrato',
							'Naproxeno sódico' => 'Naproxeno sódico',
							'Naratriptán (como clorhidrato)' => 'Naratriptán (como clorhidrato)',
							'Nebivolol' => 'Nebivolol',
							'Neomicina' => 'Neomicina',
							'Neomicina (como sulfato)' => 'Neomicina (como sulfato)',
							'Nicergolina' => 'Nicergolina',
							'Nifedipino' => 'Nifedipino',
							'Nimesulida' => 'Nimesulida',
							'Nistatina' => 'Nistatina',
							'Nitrofurantoína' => 'Nitrofurantoína',
							'Nitrofurantoína anhidra' => 'Nitrofurantoína anhidra',
							'Nitroglicerina' => 'Nitroglicerina',
							'Nomegestrol acetato' => 'Nomegestrol acetato',
							'Norepinefrina' => 'Norepinefrina',
							'Norepinetrina' => 'Norepinetrina',
							'Olanzapina' => 'Olanzapina',
							'Omeprazol' => 'Omeprazol',
							'Orlistat' => 'Orlistat',
							'Oxaliplatino' => 'Oxaliplatino',
							'Oxolamina (como citrato)' => 'Oxolamina (como citrato)',
							'Oxolamina (como fosfato)' => 'Oxolamina (como fosfato)',
							'Paclitaxel' => 'Paclitaxel',
							'Papaverina clorhidrato' => 'Papaverina clorhidrato',
							'Paracetamol' => 'Paracetamol',
							'Paracetamol (acetaminofeno)' => 'Paracetamol (acetaminofeno)',
							'Paroxetina (como Clorhidrato Hemihidrato)' => 'Paroxetina (como Clorhidrato Hemihidrato)',
							'Pediococcus acidilacti CECT 7483 1x109 UFC' => 'Pediococcus acidilacti CECT 7483 1x109 UFC',
							'Pentoxifilina' => 'Pentoxifilina',
							'Peptan' => 'Peptan',
							'Piperacilina' => 'Piperacilina',
							'Piperonil butóxido' => 'Piperonil butóxido',
							'Piridoxina clorhidrato' => 'Piridoxina clorhidrato',
							'Piritinol diclorhidrato' => 'Piritinol diclorhidrato',
							'Piroxicam' => 'Piroxicam',
							'Potasio gluconato' => 'Potasio gluconato',
							'Pramipexol diclorhidrato monohidrato' => 'Pramipexol diclorhidrato monohidrato',
							'Pramipexol diclorhidrato monohidrato (equivalente a 0,26 de Pramipexol)' => 'Pramipexol diclorhidrato monohidrato (equivalente a 0,26 de Pramipexol)',
							'Pramipexol diclorhidrato monohidrato (equivalente a 0,52 de Pramipexol)' => 'Pramipexol diclorhidrato monohidrato (equivalente a 0,52 de Pramipexol)',
							'Pramipexol diclorhidrato monohidrato (equivalente a 1,05 de Pramipexol)' => 'Pramipexol diclorhidrato monohidrato (equivalente a 1,05 de Pramipexol)',
							'Prednisona' => 'Prednisona',
							'Pregabalina' => 'Pregabalina',
							'Primidona' => 'Primidona',
							'Promestrieno' => 'Promestrieno',
							'Propranolol clorhidrato' => 'Propranolol clorhidrato',
							'Pseudoefedrina clorhidrato' => 'Pseudoefedrina clorhidrato',
							'Pseudoefedrina sulfato' => 'Pseudoefedrina sulfato',
							'Psyllium' => 'Psyllium',
							'Quetiapina (Quetiapina Fumarato)' => 'Quetiapina (Quetiapina Fumarato)',
							'Ranitidina Clorhidrato' => 'Ranitidina Clorhidrato',
							'Reslizumab' => 'Reslizumab',
							'Risperidona' => 'Risperidona',
							'Rosuvastatina (como rosuvastatina cálcica)' => 'Rosuvastatina (como rosuvastatina cálcica)',
							'Rosuvastatina (como sal cálcica)' => 'Rosuvastatina (como sal cálcica)',
							'Sacarosa' => 'Sacarosa',
							'Salbutamol (como sulfato)' => 'Salbutamol (como sulfato)',
							'Salmeterol (como Xinafoato)' => 'Salmeterol (como Xinafoato)',
							'Sertralina (como clorhidrato)' => 'Sertralina (como clorhidrato)',
							'Sildenafil (como citrato)' => 'Sildenafil (como citrato)',
							'Sulfato Ferroso' => 'Sulfato Ferroso',
							'Sulfato de bleomicina' => 'Sulfato de bleomicina',
							'Tacrolimus' => 'Tacrolimus',
							'Tadalafilo' => 'Tadalafilo',
							'Tamsulosina Clorhidrato' => 'Tamsulosina Clorhidrato',
							'Tazobactam' => 'Tazobactam',
							'Telmisartán' => 'Telmisartán',
							'Tenofovir disoproxil fumarato' => 'Tenofovir disoproxil fumarato',
							'Terbinafina (como clorhidrato)' => 'Terbinafina (como clorhidrato)',
							'Terbinafina Clorhidrato' => 'Terbinafina Clorhidrato',
							'Tetraciclina Clorhidrato' => 'Tetraciclina Clorhidrato',
							'Tiamina Clorhidrato' => 'Tiamina Clorhidrato',
							'Tibolona' => 'Tibolona',
							'Timolol (como maleato)' => 'Timolol (como maleato)',
							'Tinidazol' => 'Tinidazol',
							'Tioridazina clorhidrato' => 'Tioridazina clorhidrato',
							'Tiotropio' => 'Tiotropio',
							'Tiotropio (como Bromuro de Tiotropio)' => 'Tiotropio (como Bromuro de Tiotropio)',
							'Tolnaftato' => 'Tolnaftato',
							'Tramadol clorhidrato' => 'Tramadol clorhidrato',
							'Trazodona clorhidrato' => 'Trazodona clorhidrato',
							'Triamtereno' => 'Triamtereno',
							'Trihexifenidilo clorhidrato' => 'Trihexifenidilo clorhidrato',
							'Valganciclovir (como clorhidrato)' => 'Valganciclovir (como clorhidrato)',
							'Valsartán' => 'Valsartán',
							'Vancomicina' => 'Vancomicina',
							'Vaselina líquida medicinal' => 'Vaselina líquida medicinal',
							'Venlafaxina (como clorhidrato)' => 'Venlafaxina (como clorhidrato)',
							'Vinblastina Sulfato' => 'Vinblastina Sulfato',
							'Vitamina A' => 'Vitamina A',
							'Vitamina C' => 'Vitamina C',
							'Vitamina D3' => 'Vitamina D3',
							'Ácido Alendrónico' => 'Ácido Alendrónico',
							'Ácido Ascórbico' => 'Ácido Ascórbico',
							'Ácido Clavulánico (como sal potásica)' => 'Ácido Clavulánico (como sal potásica)',
							'Ácido Fólico' => 'Ácido Fólico',
							'Ácido Ibandrónico (como Ibandronato Sódico Monohidrato)' => 'Ácido Ibandrónico (como Ibandronato Sódico Monohidrato)',
							'Ácido Mefenámico' => 'Ácido Mefenámico',
							'Ácido clavulánico' => 'Ácido clavulánico',
							'Óxido de zinc' => 'Óxido de zinc',
						),
						'default_value' => false,
						'allow_null' => 0,
						'multiple' => 0,
						'ui' => 1,
						'ajax' => 1,
						'return_format' => 'value',
						'placeholder' => '',
						'parent_repeater' => 'field_576944bab0bd9',
					),
					array(
						'key' => 'field_576944eeb0bdb',
						'label' => 'Concentración',
						'name' => 'concentracion',
						'aria-label' => '',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
						'readonly' => 0,
						'disabled' => 0,
						'parent_repeater' => 'field_576944bab0bd9',
					),
				),
			),
			array(
				'key' => 'field_5c73f14fdc45b',
				'label' => 'Presentación',
				'name' => 'presentacion',
				'aria-label' => '',
				'type' => 'repeater',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'collapsed' => '',
				'min' => 0,
				'max' => 0,
				'layout' => 'table',
				'button_label' => 'Agregar Fila',
				'rows_per_page' => 20,
				'sub_fields' => array(
					array(
						'key' => 'field_5c73f160dc45c',
						'label' => 'Cantidad',
						'name' => 'cantidad',
						'aria-label' => '',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
						'parent_repeater' => 'field_5c73f14fdc45b',
					),
					array(
						'key' => 'field_5c73f16ddc45d',
						'label' => 'Medida',
						'name' => 'medida',
						'aria-label' => '',
						'type' => 'taxonomy',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'taxonomy' => 'formato',
						'field_type' => 'select',
						'allow_null' => 0,
						'add_term' => 1,
						'save_terms' => 0,
						'load_terms' => 0,
						'return_format' => 'object',
						'multiple' => 0,
						'bidirectional_target' => array(),
						'parent_repeater' => 'field_5c73f14fdc45b',
					),
					array(
						'key' => 'field_5c73f19ddc45e',
						'label' => 'Tipo de producto',
						'name' => 'tipo_de_producto',
						'aria-label' => '',
						'type' => 'select',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							-1 => 'Todos',
						),
						'default_value' => -1,
						'allow_null' => 0,
						'multiple' => 0,
						'ui' => 0,
						'return_format' => 'value',
						'ajax' => 0,
						'placeholder' => '',
						'parent_repeater' => 'field_5c73f14fdc45b',
					),
				),
			),
			array(
				'key' => 'field_5fc57bb3d44ff',
				'label' => 'Videos',
				'name' => 'videos',
				'aria-label' => '',
				'type' => 'repeater',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'collapsed' => '',
				'min' => 0,
				'max' => 0,
				'layout' => 'table',
				'button_label' => 'Agregar video',
				'rows_per_page' => 20,
				'sub_fields' => array(
					array(
						'key' => 'field_5fc636aa925b7',
						'label' => 'Descripción',
						'name' => 'descripcion',
						'aria-label' => '',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
						'parent_repeater' => 'field_5fc57bb3d44ff',
					),
					array(
						'key' => 'field_5fc57bd4d4500',
						'label' => 'Video',
						'name' => 'video',
						'aria-label' => '',
						'type' => 'oembed',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '50',
							'class' => '',
							'id' => '',
						),
						'width' => 320,
						'height' => 480,
						'parent_repeater' => 'field_5fc57bb3d44ff',
					),
					array(
						'key' => 'field_5fc636bd925b8',
						'label' => 'Thumbnail',
						'name' => 'thumbnail',
						'aria-label' => '',
						'type' => 'image',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'return_format' => 'array',
						'preview_size' => 'medium',
						'library' => 'all',
						'min_width' => '',
						'min_height' => '',
						'min_size' => '',
						'max_width' => '',
						'max_height' => '',
						'max_size' => '',
						'mime_types' => '',
						'parent_repeater' => 'field_5fc57bb3d44ff',
					),
				),
			),
			array(
				'key' => 'field_5fc57d1ee05d3',
				'label' => 'Enlaces y Redes Sociales',
				'name' => 'datos_redes_y_sitio',
				'aria-label' => '',
				'type' => 'group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'block',
				'sub_fields' => array(
					array(
						'key' => 'field_5fc57f39e05d4',
						'label' => 'Enlaces',
						'name' => 'enlaces',
						'aria-label' => '',
						'type' => 'repeater',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '50',
							'class' => '',
							'id' => '',
						),
						'collapsed' => '',
						'min' => 0,
						'max' => 0,
						'layout' => 'table',
						'button_label' => 'Agregar Enlace',
						'rows_per_page' => 20,
						'sub_fields' => array(
							array(
								'key' => 'field_5fc57f59e05d5',
								'label' => 'Enlace',
								'name' => 'enlace',
								'aria-label' => '',
								'type' => 'link',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'return_format' => 'array',
								'parent_repeater' => 'field_5fc57f39e05d4',
							),
						),
					),
					array(
						'key' => 'field_5fc57f8ce05d6',
						'label' => 'Redes Sociales',
						'name' => 'redes_sociales',
						'aria-label' => '',
						'type' => 'repeater',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '50',
							'class' => '',
							'id' => '',
						),
						'collapsed' => '',
						'min' => 0,
						'max' => 0,
						'layout' => 'table',
						'button_label' => 'Agregar Red Social',
						'rows_per_page' => 20,
						'sub_fields' => array(
							array(
								'key' => 'field_5fc57fa4e05d7',
								'label' => 'Red Social',
								'name' => 'red_social',
								'aria-label' => '',
								'type' => 'select',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'choices' => array(
									'fb.svg' => 'Facebook',
									'pi.svg' => 'Pinterest',
									'in.png' => 'Instagram',
									'yu.svg' => 'Youtube',
									'twitter.svg' => 'Twitter',
									'spotify.svg' => 'Spotify',
								),
								'default_value' => false,
								'allow_null' => 0,
								'multiple' => 0,
								'ui' => 0,
								'return_format' => 'value',
								'ajax' => 0,
								'placeholder' => '',
								'parent_repeater' => 'field_5fc57f8ce05d6',
							),
							array(
								'key' => 'field_5fc638838a328',
								'label' => 'URL de la red social',
								'name' => 'url_de_la_red_social',
								'aria-label' => '',
								'type' => 'url',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'parent_repeater' => 'field_5fc57f8ce05d6',
							),
						),
					),
				),
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'producto',
				),
			),
		),
		'menu_order' => -1,
		'position' => 'acf_after_title',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
		'show_in_rest' => 0,
		'modified' => 1683810601,
	));
});
